lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, get_friend_list, friend_list


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^friend-list/$', friend_list, name='friend-list'),
    url(r'^get-friend-list/$', get_friend_list, name='get-friend-list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1
from lab_2.views import index as index_lab2
from lab_2_addon.views import index as index_lab2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url="/lab-4/", permanent = "true"),name='index'),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.forms.models import model_to_dict
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada
    page = request.GET.get('page', '1')
    try:
        page = int(page)
        response_mahasiswa = csui_helper.instance.get_mahasiswa_list(page=page)
        mahasiswa_list = response_mahasiswa["results"]
    except Exception:
        return HttpResponseRedirect('/lab-7/')

    friend_list = Friend.objects.all()
    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list, "next_page": page + 1, "prev_page": page - 1}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)


@csrf_exempt
def get_friend_list(request):
    # data = serializers.serialize('json', Friend.objects.all())
    data = [model_to_dict(friend) for friend in Friend.objects.all()]
    return JsonResponse({'results': data})

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        if (not is_npm_taken(npm)):
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return JsonResponse(data)
        return JsonResponse({'message': 'mahasiswa sudah ditambahkan sebagai teman'}, status=400)

@csrf_exempt
def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return JsonResponse({'message': 'mahasiswa dihapus dari daftar teman'}, status=204)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    is_taken = is_npm_taken(npm)
    data = {
        'is_taken': is_taken
    }
    return JsonResponse(data)


def is_npm_taken(npm):
    return (Friend.objects.filter(npm=npm).count() != 0)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> friend Fasilkom</h2>
                <div id="friend-list" class="list-group">

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
    <script>
        var removeFriend = function(id) {
            $.ajax({
                method: "DELETE",
                url: "/lab-7/delete-friend/" + id + "/",
                success : function (response) {
                    console.log('sukses');
                    $('#friends-' + id).remove();
                },
                error : function (error) {
                    console.log('gagal');
                }
            });
        };

        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url "lab-7:get-friend-list" %}",
                success: function (response) {
                    friends = response.results;
                    for (i = 0; i < friends.length; i++){
                        html = '<a class="list-group-item clearfix" id="friends-' + friends[i].id + '">' +
                            friends[i].friend_name + ' (' + friends[i].npm + ')' +
                            '<span class="pull-right">' +
                            '<span class="btn btn-xs btn-default" onClick=removeFriend(' + friends[i].id + ')>' +
                            'Hapus teman</span></span></a>';
                        $("#friend-list").append(html)
                    }
                },
                error: function(error){
                    console.log('Failed to load friend list');
                }
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                <a href='?page={{ prev_page }}'> prev </a>
                <a href='?page={{ next_page }}'> next </a>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name + ' (' + friend.npm + ')'
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_taken) {
                    alert("Mahasiswa tersebut sudah ditambahkan sebagai teman");
                }
            }
        });
    });
</script>
{% endblock %}